### ISSUE TITLE
self.output instead return statement

### ISSUE THREAD

**Issue by dridk** [Aluriak/munin#1]
Currently, methods return string to print into Chat room. 
It would be better to have a method dedicated for this task : 

```
def todolist_add(self, matched_groups):
    self.write("start computation...")
    a = [ i ** 2 for i in range(100000)]
    self.write("end computation")
```

**Comment by Aluriak** [comment]
Seems to be already possible with Bot.send_message().

Is a proxy in Functionnality class necessary ?

**Comment by dridk** [comment]
didn't see. Not necessary actually
