### ISSUE TITLE
Dynamic and smart methods 

### ISSUE THREAD

**Issue by dridk** [Aluriak/munin#2]
Currently , we have to register each command. It's so borring .... 
I prefer to have a way like many python Rest application : 

```
class TodoList(Feature) :
    name = "todo" 
    def action_add(self, args):
           self.write("this is automatically called with  'munin todo add ')  

   def add(self, args):
        print("just a methods...)
```

**Comment by dridk** [comment]
I didn't notice...  I was looking into ToDoList.py which have a dictionnary of command. Seems it's useless

**Comment by Aluriak** [comment]
Can be implemented, but for many modules this is unsufficient.
We need a test in another Plugin base class, or on the top of the already existing Plugin class.

**Comment by dridk** [comment]
give me some exampe of module for which that's unsufficient.

**Comment by Aluriak** [comment]
Corrector need to react to all messages. A special method (action_all for example) can assure that. However, the detection of correction (s/.*/.* form) is very much simpler with a regex. 

Without regex, a plugin can only react to simple shapes of messages.
As said before, the better way to integrate this feature is probably to add it, without replacement of current system.
In fact, there are not exclusive : messages that fit for a action_*() method will not be sent to Plugin.do_command() method.
