### ISSUE TITLE
Rename Functionnality by Plugin or Module or Feature

### ISSUE THREAD

**Issue by dridk** [Aluriak/munin#3]
Functionnality is too big, non sens, and boring ! 
I suggest to rename it to "Module", or "Plugin" or "Feature"

**Comment by Aluriak** [comment]
Plugin seems to be the better name ; Module belongs to Python vocabulary, and Feature sounds to be not exactly what Functionnality is.

Please do it if you want it quickly.

**Comment by Aluriak** [comment]
It's done !
