### ISSUE TITLE
Regexp should not be used as top ...

### ISSUE THREAD

**Issue by dridk** [Aluriak/munin#5]
Actually you are using regexp to detect main arguments.. I prefere something like #2 

```
todo add bonjour toi

class TodoList(Feature):
    def action_add(*args):
           # args[0] = "bonjour"
           #args[1]  = "toi"
```

**Comment by dridk** [comment]
... I cannot do anything with regexp, because it use fullmatch.... Please tell me you are agree and I will convert your code to something looking like : http://flask.pocoo.org/   ! See #2

**Comment by Aluriak** [comment]
Currently, default behavior is defined in Plugin.accept_message() method.
It can be overrided in subclasses.

**Comment by Aluriak** [comment]
I close this one because all what you need is to redefine behavior in an (abstract) subclass of Plugin.
